#!/bin/bash
BIN_PATH="$(git rev-parse --show-toplevel)/node_modules/.bin"

eslint() {
    ESLINT="$BIN_PATH/eslint"

    # Check for eslint
    if [[ ! -x "$ESLINT" ]]; then
        printf "\t\033[41mPlease install ESLint\033[0m\n"
        exit 1
    fi

    echo "Linting files"

    $ESLINT

    if [[ $? == 0 ]]; then
        printf "\n\033[1;32mLint Passed\033[0m\n"
    else
        printf "\n\033[41mLint Failed:\033[0m Fix lint errors and try again!\n"
        exit 1
    fi
}

jest() {
    JEST="$BIN_PATH/jest"

    # Check for jest
    if [[ ! -x "$JEST" ]]; then
        printf "\t\033[41mPlease install Jest\033[0m\n"
        exit 1
    fi

    echo "Testing files"

    $JEST --bail

    if [[ $? == 0 ]]; then
        printf "\n\033[1;32mTest Passed\033[0m\n"
    else
        printf "\n\033[41mTest Failed:\033[0m Fix test errors and try again!\n"
        exit 1
    fi
}

eslint
jest

exit $?
